import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { StoreProvider } from "./StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Trello Task Management",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon/Tr-icon.png'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#F7F7F7]`}>
        <StoreProvider>
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
